In [22]:
import numpy as np

# 수치미분 함수

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

# sigmoid 함수

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [13]:
# LogicGate Class

class LogicGate:
    
    def __init__(self, gate_name, xdata, tdata):  # xdata, tdata => numpy.array(...)
        
        self.name = gate_name
        
        # 입력 데이터, 정답 데이터 초기화
        self.__xdata = xdata.reshape(4,2)
        self.__tdata = tdata.reshape(4,1)
        
        # 가중치 W, 바이어스 b 초기화
        self.__W = np.random.rand(2,1)  # weight, 2 X 1 matrix
        self.__b = np.random.rand(1)
                        
        # 학습률 learning rate 초기화
        self.__learning_rate = 1e-2
        
    # 손실함수
    def __loss_func(self):
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z = np.dot(self.__xdata, self.__W) + self.__b
        y = sigmoid(z)
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )      
    
    # 손실 값 계산
    def error_val(self):
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z = np.dot(self.__xdata, self.__W) + self.__b
        y = sigmoid(z)
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )

     # 수치미분을 이용하여 손실함수가 최소가 될때 까지 학습하는 함수
    def train(self):
        
        f = lambda x : self.__loss_func()
        
        print("Initial error value = ", self.error_val())
        
        for step in  range(8001):
            
            self.__W -= self.__learning_rate * numerical_derivative(f, self.__W)
    
            self.__b -= self.__learning_rate * numerical_derivative(f, self.__b)
    
            if (step % 400 == 0):
                print("step = ", step, "error value = ", self.error_val())
                
                
    # 미래 값 예측 함수
    def predict(self, input_data):
        
        z = np.dot(input_data, self.__W) + self.__b
        y = sigmoid(z)
    
        if y > 0.5:
            result = 1  # True
        else:
            result = 0  # False
    
        return y, result

In [14]:
# AND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 0, 0, 1])

and_obj = LogicGate("AND", xdata, tdata)

and_obj.train()

Initial error value =  2.939195787943593
step =  0 error value =  2.9217018119604243
step =  400 error value =  1.5522680896153507
step =  800 error value =  1.1501342859706898
step =  1200 error value =  0.9233570284094701
step =  1600 error value =  0.7741229676970495
step =  2000 error value =  0.6670504601436105
step =  2400 error value =  0.5859628201166619
step =  2800 error value =  0.522234690105263
step =  3200 error value =  0.4707654690309148
step =  3600 error value =  0.42831094908145806
step =  4000 error value =  0.39269408109686565
step =  4400 error value =  0.36239281794112493
step =  4800 error value =  0.3363079835053868
step =  5200 error value =  0.3136245747300036
step =  5600 error value =  0.2937248800920194
step =  6000 error value =  0.27613191715846236
step =  6400 error value =  0.2604714095633623
step =  6800 error value =  0.24644552503466244
step =  7200 error value =  0.23381431037125622
step =  7600 error value =  0.22238230003193793
step =  8000 error

In [15]:
# AND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(and_obj.predict(data))

(array([0.00037388]), 0)
(array([0.05996063]), 0)
(array([0.0599576]), 0)
(array([0.91580545]), 1)


In [16]:
# OR Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 1])

or_obj = LogicGate("OR", xdata, tdata)

or_obj.train()

Initial error value =  1.781572106278876
step =  0 error value =  1.7747900747059362
step =  400 error value =  1.04150633664316
step =  800 error value =  0.7658265348595408
step =  1200 error value =  0.6003773550883746
step =  1600 error value =  0.49099014853317374
step =  2000 error value =  0.4137588200321863
step =  2400 error value =  0.35658193858031945
step =  2800 error value =  0.3126985001199069
step =  3200 error value =  0.27804723479077775
step =  3600 error value =  0.25004918722168573
step =  4000 error value =  0.22699264895736018
step =  4400 error value =  0.20769964596834062
step =  4800 error value =  0.1913346015444583
step =  5200 error value =  0.1772893649396337
step =  5600 error value =  0.16511139089868646
step =  6000 error value =  0.1544573620316915
step =  6400 error value =  0.14506236863314
step =  6800 error value =  0.13671890601416797
step =  7200 error value =  0.1292622407647886
step =  7600 error value =  0.12256001103061798
step =  8000 error 

In [17]:
# OR Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(or_obj.predict(data))

(array([0.06333503]), 0)
(array([0.97481668]), 1)
(array([0.97479851]), 1)
(array([0.99995484]), 1)


In [18]:
# NAND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([1, 1, 1, 0])

nand_obj = LogicGate("NAND", xdata, tdata)

nand_obj.train()

Initial error value =  2.8512327966080475
step =  0 error value =  2.8460847681369996
step =  400 error value =  1.6697591564681857
step =  800 error value =  1.2083567408683091
step =  1200 error value =  0.9590649320281897
step =  1600 error value =  0.798697519259999
step =  2000 error value =  0.6851615408270308
step =  2400 error value =  0.5999249015352528
step =  2800 error value =  0.5333486432736853
step =  3200 error value =  0.47982886454436435
step =  3600 error value =  0.43584442274920926
step =  4000 error value =  0.3990538810290387
step =  4400 error value =  0.3678318121188081
step =  4800 error value =  0.3410110192630409
step =  5200 error value =  0.31773008846647355
step =  5600 error value =  0.2973386821048589
step =  6000 error value =  0.2793363010139589
step =  6400 error value =  0.26333135266842755
step =  6800 error value =  0.24901301698997325
step =  7200 error value =  0.23613144087402593
step =  7600 error value =  0.22448350409997062
step =  8000 erro

In [19]:
# NAND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(nand_obj.predict(data))

(array([0.99961559]), 1)
(array([0.93952403]), 1)
(array([0.9395207]), 1)
(array([0.08492663]), 0)


In [20]:
# XOR Gate 객체 생성

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 0])


xor_obj = LogicGate("XOR", xdata, tdata)

xor_obj.train()

Initial error value =  3.815300595667015
step =  0 error value =  3.7919925137021906
step =  400 error value =  2.779421892394409
step =  800 error value =  2.7743989357539007
step =  1200 error value =  2.7730841747738957
step =  1600 error value =  2.772726254787915
step =  2000 error value =  2.772626814657888
step =  2400 error value =  2.7725989027018154
step =  2800 error value =  2.7725910285985305
step =  3200 error value =  2.772588801874167
step =  3600 error value =  2.772588171442833
step =  4000 error value =  2.7725879928553447
step =  4400 error value =  2.7725879422519433
step =  4800 error value =  2.772587927911471
step =  5200 error value =  2.772587923847287
step =  5600 error value =  2.7725879226954366
step =  6000 error value =  2.772587922368981
step =  6400 error value =  2.7725879222764567
step =  6800 error value =  2.772587922250233
step =  7200 error value =  2.772587922242801
step =  7600 error value =  2.772587922240694
step =  8000 error value =  2.77258

In [21]:
test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(xor_obj.predict(data))

(array([0.49999972]), 0)
(array([0.49999996]), 0)
(array([0.49999996]), 0)
(array([0.50000019]), 1)


In [24]:
# XOR 을 NAND + OR => AND 조합으로 계산함
input_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

s1 = []    # NAND 출력
s2 = []    # OR 출력

new_input_data = []  # AND 입력
final_output = []    # AND 출력

for index in range(len(input_data)):
    
    s1 = nand_obj.predict(input_data[index])  # NAND 출력
    s2 = or_obj.predict(input_data[index])    # OR 출력
    
    new_input_data.append(s1[-1])    # AND 입력
    new_input_data.append(s2[-1])    # AND 입력
    
    (sigmoid_val, logical_val) = and_obj.predict(np.array(new_input_data))
    
    final_output.append(logical_val)    # AND 출력, 즉 XOR 출력    
    new_input_data = []    # AND 입력 초기화


for index in range(len(input_data)):    
    print(input_data[index], " = ", final_output[index], end='')
    print("\n")

[0 0]  =  0

[0 1]  =  1

[1 0]  =  1

[1 1]  =  0

