In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.5.0


In [2]:
x_data = np.array([2, 4, 6, 8, 10,
                   12, 14, 16, 18, 20]).astype('float32')

t_data = np.array([0, 0, 0, 0, 0,
                   0, 1, 1, 1, 1]).astype('float32')

In [4]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(8, input_shape=(1,), 
                                activation='sigmoid'))


model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [5]:
model.compile(tf.keras.optimizers.SGD(learning_rate=0.1),
              loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 8)                 16        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [6]:
hist = model.fit(x_data, t_data, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 386ms/step - loss: 0.7294 - accuracy: 0.4000
Epoch 2/500
1/1 [==============================] - 0s 998us/step - loss: 0.7081 - accuracy: 0.4000
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6913 - accuracy: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 998us/step - loss: 0.6780 - accuracy: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 997us/step - loss: 0.6675 - accuracy: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6591 - accuracy: 0.6000
Epoch 7/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6523 - accuracy: 0.6000
Epoch 8/500
1/1 [==============================] - 0s 997us/step - loss: 0.6467 - accuracy: 0.7000
Epoch 9/500
1/1 [==============================] - 0s 997us/step - loss: 0.6421 - accuracy: 0.8000
Epoch 10/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6381 - accuracy: 0.8000
Epoch 11/500
1/1 

1/1 [==============================] - 0s 2ms/step - loss: 0.5615 - accuracy: 0.7000
Epoch 84/500
1/1 [==============================] - 0s 997us/step - loss: 0.5606 - accuracy: 0.7000
Epoch 85/500
1/1 [==============================] - 0s 999us/step - loss: 0.5598 - accuracy: 0.7000
Epoch 86/500
1/1 [==============================] - 0s 2ms/step - loss: 0.5590 - accuracy: 0.7000
Epoch 87/500
1/1 [==============================] - 0s 995us/step - loss: 0.5581 - accuracy: 0.7000
Epoch 88/500
1/1 [==============================] - 0s 2ms/step - loss: 0.5572 - accuracy: 0.7000
Epoch 89/500
1/1 [==============================] - 0s 997us/step - loss: 0.5564 - accuracy: 0.7000
Epoch 90/500
1/1 [==============================] - 0s 997us/step - loss: 0.5555 - accuracy: 0.7000
Epoch 91/500
1/1 [==============================] - 0s 997us/step - loss: 0.5546 - accuracy: 0.7000
Epoch 92/500
1/1 [==============================] - 0s 998us/step - loss: 0.5538 - accuracy: 0.7000
Epoch 93/500
1/1 [=

1/1 [==============================] - 0s 2ms/step - loss: 0.4800 - accuracy: 0.9000
Epoch 166/500
1/1 [==============================] - 0s 998us/step - loss: 0.4792 - accuracy: 0.9000
Epoch 167/500
1/1 [==============================] - 0s 997us/step - loss: 0.4785 - accuracy: 0.9000
Epoch 168/500
1/1 [==============================] - 0s 997us/step - loss: 0.4777 - accuracy: 0.9000
Epoch 169/500
1/1 [==============================] - 0s 998us/step - loss: 0.4769 - accuracy: 0.9000
Epoch 170/500
1/1 [==============================] - 0s 997us/step - loss: 0.4762 - accuracy: 0.9000
Epoch 171/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4754 - accuracy: 0.9000
Epoch 172/500
1/1 [==============================] - 0s 2ms/step - loss: 0.4747 - accuracy: 0.9000
Epoch 173/500
1/1 [==============================] - 0s 998us/step - loss: 0.4739 - accuracy: 0.9000
Epoch 174/500
1/1 [==============================] - 0s 996us/step - loss: 0.4731 - accuracy: 0.9000
Epoch 175/

1/1 [==============================] - 0s 998us/step - loss: 0.4205 - accuracy: 1.0000
Epoch 247/500
1/1 [==============================] - 0s 997us/step - loss: 0.4198 - accuracy: 1.0000
Epoch 248/500
1/1 [==============================] - 0s 997us/step - loss: 0.4191 - accuracy: 1.0000
Epoch 249/500
1/1 [==============================] - 0s 997us/step - loss: 0.4184 - accuracy: 1.0000
Epoch 250/500
1/1 [==============================] - 0s 997us/step - loss: 0.4177 - accuracy: 1.0000
Epoch 251/500
1/1 [==============================] - 0s 998us/step - loss: 0.4170 - accuracy: 1.0000
Epoch 252/500
1/1 [==============================] - 0s 1ms/step - loss: 0.4163 - accuracy: 1.0000
Epoch 253/500
1/1 [==============================] - 0s 997us/step - loss: 0.4156 - accuracy: 1.0000
Epoch 254/500
1/1 [==============================] - 0s 997us/step - loss: 0.4149 - accuracy: 1.0000
Epoch 255/500
1/1 [==============================] - 0s 997us/step - loss: 0.4142 - accuracy: 1.0000
Epoch 

1/1 [==============================] - 0s 2ms/step - loss: 0.3673 - accuracy: 1.0000
Epoch 328/500
1/1 [==============================] - 0s 998us/step - loss: 0.3667 - accuracy: 1.0000
Epoch 329/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3661 - accuracy: 1.0000
Epoch 330/500
1/1 [==============================] - 0s 996us/step - loss: 0.3655 - accuracy: 1.0000
Epoch 331/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3649 - accuracy: 1.0000
Epoch 332/500
1/1 [==============================] - 0s 998us/step - loss: 0.3643 - accuracy: 1.0000
Epoch 333/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3637 - accuracy: 1.0000
Epoch 334/500
1/1 [==============================] - 0s 997us/step - loss: 0.3631 - accuracy: 1.0000
Epoch 335/500
1/1 [==============================] - 0s 997us/step - loss: 0.3625 - accuracy: 1.0000
Epoch 336/500
1/1 [==============================] - 0s 997us/step - loss: 0.3619 - accuracy: 1.0000
Epoch 337/50

1/1 [==============================] - 0s 997us/step - loss: 0.3218 - accuracy: 1.0000
Epoch 409/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3213 - accuracy: 1.0000
Epoch 410/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3208 - accuracy: 1.0000
Epoch 411/500
1/1 [==============================] - 0s 997us/step - loss: 0.3203 - accuracy: 1.0000
Epoch 412/500
1/1 [==============================] - 0s 997us/step - loss: 0.3198 - accuracy: 1.0000
Epoch 413/500
1/1 [==============================] - 0s 998us/step - loss: 0.3193 - accuracy: 1.0000
Epoch 414/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3187 - accuracy: 1.0000
Epoch 415/500
1/1 [==============================] - 0s 998us/step - loss: 0.3182 - accuracy: 1.0000
Epoch 416/500
1/1 [==============================] - 0s 2ms/step - loss: 0.3177 - accuracy: 1.0000
Epoch 417/500
1/1 [==============================] - 0s 998us/step - loss: 0.3172 - accuracy: 1.0000
Epoch 418/50

1/1 [==============================] - 0s 999us/step - loss: 0.2838 - accuracy: 1.0000
Epoch 490/500
1/1 [==============================] - 0s 2ms/step - loss: 0.2834 - accuracy: 1.0000
Epoch 491/500
1/1 [==============================] - 0s 2ms/step - loss: 0.2830 - accuracy: 1.0000
Epoch 492/500
1/1 [==============================] - 0s 998us/step - loss: 0.2825 - accuracy: 1.0000
Epoch 493/500
1/1 [==============================] - 0s 997us/step - loss: 0.2821 - accuracy: 1.0000
Epoch 494/500
1/1 [==============================] - 0s 998us/step - loss: 0.2817 - accuracy: 1.0000
Epoch 495/500
1/1 [==============================] - 0s 997us/step - loss: 0.2813 - accuracy: 1.0000
Epoch 496/500
1/1 [==============================] - 0s 997us/step - loss: 0.2809 - accuracy: 1.0000
Epoch 497/500
1/1 [==============================] - 0s 998us/step - loss: 0.2804 - accuracy: 1.0000
Epoch 498/500
1/1 [==============================] - 0s 2ms/step - loss: 0.2800 - accuracy: 1.0000
Epoch 499/

In [6]:
test_data = np.array([0.5, 3.0, 3.5, 
                      11.0, 13.0, 31.0])

sigmoid_value = model.predict(test_data)

logical_value = tf.cast(sigmoid_value > 0.5,
                      dtype=tf.float32)

for i in range(len(test_data)):
    print(test_data[i], 
          sigmoid_value[i], 
          logical_value.numpy()[i])

0.5 [0.04223922] [0.]
3.0 [0.05836764] [0.]
3.5 [0.06577787] [0.]
11.0 [0.39917535] [0.]
13.0 [0.5249193] [1.]
31.0 [0.8609705] [1.]


In [7]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 8) dtype=float32, numpy=
 array([[ 0.9090736 , -0.18241355, -1.0119302 ,  0.1490751 ,  0.54939204,
          0.13127813,  0.13950464, -0.1802529 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(8,) dtype=float32, numpy=
 array([ 0.0556334 ,  1.338934  , -0.11622923, -0.6382603 ,  0.01752405,
        -0.17451894, -0.4021825 ,  1.2973777 ], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(8, 1) dtype=float32, numpy=
 array([[-0.43934634],
        [-2.4066896 ],
        [ 0.6325082 ],
        [ 1.3539454 ],
        [-0.03330512],
        [ 0.5639338 ],
        [ 1.0730162 ],
        [-2.3513427 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([-0.57455003], dtype=float32)>]